name: CI
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
        os:
          - ubuntu-latest
        arch:
          - x64
    env:
      JULIA_PKG_USE_CLI_GIT: true  
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: julia-actions/setup-julia@512e2ab44f5848ea62bddd21d1ee906e989b0360
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@8608484607cba0bdb5437a7bad85d6502499d029
      - uses: julia-actions/julia-buildpkg@90dd6f23eb49626e4e6612cb9d64d456f86e6a1c
      - uses: julia-actions/julia-runtest@d0c4f093badade621cd041bba567d1e832480ac2